### ISSUE TITLE
Gdspy 1.4

### ISSUE THREAD

**Issue by LukiLeu** [Aypac/GDSLatexConverter#13]
The converter does not work with gdspy version 1.4. Switching back to version 1.3.2 resolved the issue.

**Comment by Aypac** [comment]
Thank you. Somehow I missed the notification. Fixed it for now by fixing the version number in the setup.py (see 0ea242f332309477d410c33d54a0b93b5ad0a2b4).

**Comment by Aypac** [comment]
Just as a note to myself: it might make sense to adapt to the new interface of gdspy at some point.
